files:
  - url: ""
    time: 1635571593955.yml
    name: config.yaml
    selected: []
  - time: 1635571886218.yml
    name: owM4z4.yaml
    url: https://cdn.jsdelivr.net/gh/changfengoss/pub@main/data/2021_10_29/owM4z4.yaml
    selected:
      - name: GLOBAL
        now: DIRECT
      - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
        now: cfmem.com_ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
      - name: ğŸŒ å›½å¤–åª’ä½“
        now: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - name: ğŸŒ å›½å†…åª’ä½“
        now: ğŸ¯ å…¨çƒç›´è¿
      - name: â“‚ï¸ å¾®è½¯æœåŠ¡
        now: ğŸ¯ å…¨çƒç›´è¿
      - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
        now: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - name: ğŸ è‹¹æœæœåŠ¡
        now: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - name: ğŸ¯ å…¨çƒç›´è¿
        now: DIRECT
      - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
        now: REJECT
      - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
        now: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    interval: 0
    subInfo: {}
index: 1
